### ISSUE TITLE
NoMethodError: undefined method `categories' 

### ISSUE THREAD

**Issue by BorisBresciani** [gpcweb/crazy_chaarts#1]
Hello,

It is impossible to override categories :(

Code:
`chart = CrazyChaarts::LineChart.new()
chart.categories = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Ago', 'Sep', 'Oct', 'Nov', 'Dec']`

Error:
`NoMethodError: undefined method`categories' `

Thx

**Comment by gpcweb** [comment]
Hello Boris, 

Please try this

```
chart = CrazyChaarts::LineChart.new() 
chart.xAxis_categories = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Ago', 'Sep', 'Oct', 'Nov', 'Dec']
```
